### ISSUE TITLE
New Feature request - Custom ciphers

### ISSUE THREAD

**Issue by blaudp79** [dlascelles/Arithmos#2]
Hi,

I have used it to decode a couple of events and it is extremely useful.
In case you are planning to update it, I'd like to propose a new feature.

It would allow users to create and edit custom ciphers.
The idea is to use a config.cfg file in which it stores the cipher configurations.

Example content of config.cfg:

```
English Ordinal
a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z
1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26

Reverse Ordinal
a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z
26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1
```

Thanks.

**Comment by dlascelles** [comment]
Hello, I'm glad you found the application useful and thanks for the suggestion.

I'm currently not planning any major updates to it due to lack of time. It's an interesting suggestion and if I ever find the time I will look into it more.

**Comment by dlascelles** [comment]
@blaudp79 Hi, I just released a new version of the application that allows you to create custom gematria methods. Enjoy!
