### ISSUE TITLE
New Feature request - Use Negative numbers in custom Ciphers.

### ISSUE THREAD

**Issue by GematriaGuy** [dlascelles/Arithmos#3]
Hi, I tried to add negative numbers to custom Ciphers, but the program would not accept it. 
For example;   
A= -26   a=-26   B=-25   b=-25   and so on.  I think this would be a very useful Feature if added!  

Daniel, Thanks for Posting this program!  Anyone with an open mind can have a positive benefit from using this program.

**Comment by dlascelles** [comment]
Hello, the application does not accept negative values and that is by design.

It sounds like a very niche use case (for an already very niche application :smiley:), therefore I won't be investing time in it.
 
Thanks for the suggestion though!
